### ISSUE TITLE
Peer-to-peer Code Review

### ISSUE THREAD

**Issue by fredericomba** [mekinus/newsweek-clone#2]
Hello, @mekinus (Leonardo Rocha Couto). I would like to provide some insight that might help you get this project approved, so I have opened this issue with my review of your code.

- There are things that can be easily fixed. If you wrap the navigator header of the website (line 15 to line 40) in a ```div``` that uses the bootstrap classes ```d-none``` (display: none) and ```d-lg-block``` (> 1024px, then display: block), you'll hide what needs to be hidden on screens that are smaller than the large profile.

```HTML
14: <div class="d-none d-lg-block">
15: <div class="jumbotron d-flex justify-content-around header bg-orange p-3 mb-1">
...
40: </nav>
41: </div>
```

Second, remember to abide to bootstrap rules. The twelve-column bootstrap grid should have this hierarchy: container -> row -> column. **You must not place container neither container-fluid inside elements of class ```col-*``` or ```col-*-*```, because those containers might overflow the columns and break the layout**. You are doing that at lines 47, 54, 61...
Reference link: [Bootstrap layout grid](https://getbootstrap.com/docs/4.0/layout/grid/)

You are using container-fluid everywhere (which is an invitation for breaking the layout). **If you use only one container for the whole page, all of the layout breaks will be gone**. 

You can have a look at my own project, if you want to. I have only used **one** ```container-fluid``` for the entire page. Only one.
[Newsweek Clone](https://frederico-miranda.github.io/using-bootstrap/index.html)

I can share more insight with you, if you want to. [Contact me](mailto:frederico.miranda.brandao@gmail.com) if you want to have a more lengthy conversation with me.

**Comment by mekinus** [comment]
Already fixed this issues =) , Thank you for the hint !
